Sub content <<EOS
sub {
	my $url = shift;
	my @parts = split(/\//, $url);

	if ($parts[1] =~ /^(\d+)$/) {
		$CGI->{mv_nextpage} = 'content/display';
		$CGI->{code} = $1;
	}
	elsif ($parts[1]) {
		if ($parts[$#parts] =~ /^(\d+)$/) {
			$CGI->{code} = pop(@parts);
			$url = join('/', @parts);
		}

		$CGI->{mv_nextpage} = $url;
	} else {
		$CGI->{mv_nextpage} = 'content/recent';
	}

	$Values->{code} = $CGI->{code};

	return 1;
}
EOS
