Sub form_content_edit_load <<EOS
sub {
	my (@fields, @content);

	@fields = qw/title body uri/;

	$Tag->perl({tables => 'content'});

	if ($CGI->{code}) {	
		@content = $Db{content}->get_slice($CGI->{code}, \@fields);

		for (my $i = 0; $i <= @fields; $i++) {
			$Values->{$fields[$i]} = $content[$i];
		}
	}
	else {
		$Values->{title} = $Values->{body} = '';
		$Values->{uri} = $CGI->{uri};
	}
}
EOS
