Sub form_content_edit_save <<EOS
sub {
	# create new content
	my (%content, $code);

	for (qw/title body uri/) {
		$content{$_} = $CGI->{$_};
	}
	$content{uid} = $Session->{username} || 0;
	$content{type} = 'page';

	# store timestamp
	unless ($CGI->{code}) {
		$content{created} = $Tag->time({format => '%s'});
	}

	$Tag->perl({tables => 'content'});
	
	$code = $Db{content}->set_slice($CGI->{code}, %content);

	return {code => $code, page => 'content/recent'};
}
EOS
