ActionMap cart <<EOA
sub {
	# always update values and set targetpage first
	$Tag->update('values');

	$CGI->{mv_nextpage} = 'cart';

	# checkout function?
	if ($CGI->{checkout}) {
		$CGI->{mv_nextpage} = 'checkout';
		return 1;
	}

	# clear function?
	if ($CGI->{clear}) {
		$Tag->cart_clear();
	}

	# remove function?
	for (my $i = 0; $i < @$Items; $i++) {
		if ($CGI->{"zeroquantity$i"}) {
			$CGI->{"quantity$i"} = 0;
			$Tag->cart_refresh();
			return 1;
		}	    
	}

	# update quantities in the cart
	$Tag->cart_refresh();
	return 1;
}
EOA
