UserTag mangle_path Order path
UserTag mangle_path Routine <<EOR
sub {
	my $path = shift;
	$Vend::FinalPath = $path;
}
EOR

Sub init <<EOS
sub {
	if ($Tag->env('REQUEST_METHOD') eq 'POST') {
		# form submission, interception possible
		my ($form_name);

		if ($form_name = $CGI->{series}) {
			$Tag->tmp('forms', {});
			$Scratch->{forms}->{$form_name} = $Tag->form({name => $form_name});
			if ($CGI->{mv_nextpage}) {
				$Tag->mangle_path($CGI->{mv_nextpage});
			}
		}
	}	
}
EOS
