ActionMap login <<EOA
sub {
	$Tag->perl({tables => 'users'});

	$CGI->{mv_nextpage} = 'login';

	if ($Session->{logged_in}) {
		$Tag->warnings({message => 'You are already logged in as user %s',
			param => $Session->{username}});
		return 1;
	}

	# look for user submission
	if (exists $CGI->{mv_username}) {
		$Tag->perl({tables => 'users'});

		if ($CGI->{mv_username} =~ /\@/) {
			# login with email address
			$Tag->userdb({function => 'login'});
		} else {
			# login with username
			$Tag->userdb({function => 'login',
				indirect_login => 'username'});
		}

		if ($ret) {
			$Tag->warnings('Logged in successfully.');
		} else {
			$Tag->error({name => login, set => $Session->{failure}});
		}
	}

	return 1;
}
EOA
