Sub form_menus_save <<EOS
sub {
	my %menu;

	$Tag->perl({tables => 'menus'});

	$menu{menu_name} = $CGI->{menu_name};
	$menu{name} = $CGI->{name};
	$menu{url} = $CGI->{url};

	if ($CGI->{menu_code}) {
		$ret = $Db{menus}->set_slice([{dml => 'update'}, $CGI->{menu_code}], %menu);
	}
	else {
		$ret = $Db{menus}->set_slice([{dml => 'insert'}], %menu);
	}
		
	return {page => "backend/menus/$menu{menu_name}"};
}
EOS
